name: Create a new release

on:
  workflow_dispatch:
    inputs:
        releaseTag:
          description: 'Release Tag'     
          required: true
        productionRelease:
          type: boolean
          description: Mark release as production ready
jobs:
  release-ubuntu:
    name: Build for Linux
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      BUILD_TARGET: x86_64-unknown-linux-musl
      BINARY_NAME: fastn-package-proxy
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build-musl
        uses: gmiam/rust-musl-action@9e6a37bf27ecfffb6b92240ea276bea5487fa15d
        continue-on-error: false
        with:
          args: cargo build --target $BUILD_TARGET --release
      - name: Gzip Binary
        run: |
          cp target/x86_64-unknown-linux-musl/release/fastn-package-proxy .
          gzip fastn-package-proxy
      - uses: actions/upload-artifact@v2
        with:
          name: linux_musl_x86_64
          path: fastn-package-proxy.gz

  create-release:
    name: Create github tag and release
    runs-on: ubuntu-latest
    needs: [release-ubuntu]
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v2
        with:
          name: linux_musl_x86_64
          path: ~/download
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "~/download/fastn-package-proxy.gz"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.releaseTag }}
          prerelease: ${{ github.event.inputs.productionRelease && github.event.inputs.productionRelease == 'false' }}
          bodyFile: .github/RELEASE_TEMPLATE.md
